app = "brandboda-29oifg"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile"

[processes]
  app = "python3 run.py"

[[vm]]
  cpu_kind = "performance" # يجب أن يكون performance لهذا العدد من الأنوية
  cpus = 16
  memory_mb = 51200        # 50 جيجا بايت
  
[[swap]]
  size_mb = 512
